name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build ${{ matrix.config }}
        run: make CONFIG=${{ matrix.config }} build-all-platforms
      - name: Run ${{ matrix.config }} tests
        run: make CONFIG=${{ matrix.config }} test-library

  library-windows:
    name: Library (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9.2-release
          tag: 5.9.2-RELEASE
      - name: Build and test
        run: swift test

  library-evolution:
    name: Library (evolution)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  library-compatibility:
    name: Library (Swift 5.7.1)
    runs-on: macos-12
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 14.1
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Build ${{ matrix.config }}
        run: swift build -c ${{ matrix.config }}

  benchmarks:
    name: Benchmarks
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Run benchmark
        run: make benchmark

  examples:
    name: Examples
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Run tests
        run: make test-examples
